name: runeql-data update

on:
  push:
    branches: [ master, updatetest ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: runeql-transform
        uses: schmidlidev/runeql-tools/transform@main
        env:
          RUNEQL_DATA_LOAD: ${{ secrets.RUNEQL_DATA_PUSH }}
